global using BuzzAir.Data.Enums;
global using BuzzAir.Data.Models;
global using BuzzAir.Data.Models.ServicesModels;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Migrations;
global using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
