// <auto-generated />
using System;
using BuzzAir.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuzzAir.Migrations
{
    [DbContext(typeof(BuzzAirDbContext))]
    partial class BuzzAirDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuzzAir.Models.DbModels.Aircraft", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Airport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ElevationAboveSeaLevel")
                        .HasColumnType("integer");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ICAO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("IATA")
                        .IsUnique();

                    b.HasIndex("ICAO")
                        .IsUnique();

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PassengerId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PassengerId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Booking", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.BookingFlight", b =>
                {
                    b.Property<string>("FlightId")
                        .HasColumnType("text");

                    b.Property<string>("BookingId")
                        .HasColumnType("text");

                    b.HasKey("FlightId", "BookingId");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingFlights");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.BookingPassenger", b =>
                {
                    b.Property<string>("PassengerId")
                        .HasColumnType("text");

                    b.Property<string>("BookingId")
                        .HasColumnType("text");

                    b.HasKey("PassengerId", "BookingId");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingPassengers");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.ChangeLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AfterJSON")
                        .HasColumnType("text");

                    b.Property<string>("BeforeJSON")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChangeLogs");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.City", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateId")
                        .HasColumnType("text");

                    b.Property<string>("TimezoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("StateId");

                    b.HasIndex("TimezoneId");

                    b.HasIndex("Name", "StateId")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ISO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOfficiallyRecognizedCountry")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ISO")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Flight", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AircraftId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ArrivalUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceInEur")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)");

                    b.Property<int>("TakenSeats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("FlightNumber");

                    b.HasIndex("OriginId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.FlightPassenger", b =>
                {
                    b.Property<string>("FlightId")
                        .HasColumnType("text");

                    b.Property<string>("PassengerId")
                        .HasColumnType("text");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer");

                    b.HasKey("FlightId", "PassengerId", "SeatNumber");

                    b.HasIndex("PassengerId");

                    b.ToTable("FlightPassengers");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Passenger", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.PassengerService", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasColumnType("text");

                    b.Property<string>("PassengerId")
                        .HasColumnType("text");

                    b.HasKey("ServiceId", "PassengerId");

                    b.HasIndex("PassengerId");

                    b.ToTable("PassengerServices");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Payment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("AmountInEur")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CVC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Card")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardHolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(29, 28)
                        .HasColumnType("numeric(29,28)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasDiscriminator<string>("ServiceType").HasValue("Service");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.State", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Timezone", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Offset")
                        .HasColumnType("interval");

                    b.Property<bool>("UsesDST")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Timezones");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.TravelDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BirthCountryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NationalityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassengerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BirthCountryId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("PassengerId")
                        .IsUnique();

                    b.ToTable("TravelDocuments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Services.AirportCheckIn", b =>
                {
                    b.HasBaseType("BuzzAir.Models.DbModels.Service");

                    b.HasDiscriminator().HasValue("AirportCheckIn");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Services.Baggage", b =>
                {
                    b.HasBaseType("BuzzAir.Models.DbModels.Service");

                    b.Property<string>("BaggageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kilos")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Baggage");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Services.Flexibility", b =>
                {
                    b.HasBaseType("BuzzAir.Models.DbModels.Service");

                    b.HasDiscriminator().HasValue("Flexibility");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Services.OnTimeArrival", b =>
                {
                    b.HasBaseType("BuzzAir.Models.DbModels.Service");

                    b.HasDiscriminator().HasValue("OnTimeArrival");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Services.Priority", b =>
                {
                    b.HasBaseType("BuzzAir.Models.DbModels.Service");

                    b.HasDiscriminator().HasValue("Priority");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Services.Seat", b =>
                {
                    b.HasBaseType("BuzzAir.Models.DbModels.Service");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Seat");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Airport", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.City", "City")
                        .WithMany("Airports")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.ApplicationUser", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuzzAir.Models.DbModels.Passenger", "Passenger")
                        .WithOne("User")
                        .HasForeignKey("BuzzAir.Models.DbModels.ApplicationUser", "PassengerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Booking", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.Payment", "Payment")
                        .WithOne("Booking")
                        .HasForeignKey("BuzzAir.Models.DbModels.Booking", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.BookingFlight", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.Booking", "Booking")
                        .WithMany("Flights")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuzzAir.Models.DbModels.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.BookingPassenger", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuzzAir.Models.DbModels.Passenger", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.City", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuzzAir.Models.DbModels.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuzzAir.Models.DbModels.Timezone", "Timezone")
                        .WithMany("Cities")
                        .HasForeignKey("TimezoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("State");

                    b.Navigation("Timezone");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Flight", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuzzAir.Models.DbModels.Airport", "Destination")
                        .WithMany("FlightsTo")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuzzAir.Models.DbModels.Airport", "Origin")
                        .WithMany("FlightsFrom")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.FlightPassenger", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.Flight", "Flight")
                        .WithMany("Passengers")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuzzAir.Models.DbModels.Passenger", "Passenger")
                        .WithMany("Flights")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.PassengerService", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.Passenger", "Passenger")
                        .WithMany("Services")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuzzAir.Models.DbModels.Service", "Service")
                        .WithMany("Passengers")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.State", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.TravelDocument", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.Country", "BirthCountry")
                        .WithMany("DocumentsBirthCountries")
                        .HasForeignKey("BirthCountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuzzAir.Models.DbModels.Country", "Nationality")
                        .WithMany("DocumentsNationalities")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuzzAir.Models.DbModels.Passenger", "Passenger")
                        .WithOne("Document")
                        .HasForeignKey("BuzzAir.Models.DbModels.TravelDocument", "PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BirthCountry");

                    b.Navigation("Nationality");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuzzAir.Models.DbModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BuzzAir.Models.DbModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Aircraft", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Airport", b =>
                {
                    b.Navigation("FlightsFrom");

                    b.Navigation("FlightsTo");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Booking", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.City", b =>
                {
                    b.Navigation("Airports");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("DocumentsBirthCountries");

                    b.Navigation("DocumentsNationalities");

                    b.Navigation("States");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Flight", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Passenger", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Document")
                        .IsRequired();

                    b.Navigation("Flights");

                    b.Navigation("Services");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Payment", b =>
                {
                    b.Navigation("Booking")
                        .IsRequired();
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Service", b =>
                {
                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("BuzzAir.Models.DbModels.Timezone", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
